name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://penta.pactflow.io
  PACT_PROVIDER: pactflow-example-provider
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  REACT_APP_API_BASE_URL: http://localhost:3001
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  consumer-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Verify Consumer Tests
        run: mvn -f ./consumer/ verify -Dpact.verifier.publishResults=true -Dpact.provider.version=1.0-SNAPSHOT
      - name: Publish customer tests
        run: mvn -f ./consumer/  pact:publish

  provider-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Verify Provider Tests
        run: mvn -f ./provider/ verify -Dpact.verifier.publishResults=true -Dpact.provider.version=1.0-SNAPSHOT

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy-consumer:
    runs-on: ubuntu-latest
    needs: consumer-publish
    steps:
      - uses: actions/checkout@v3
      - name: Can I deploy consumer?
        run: mvn -f ./consumer/ pact:can-i-deploy -Dpacticipant='ProductCatalogue' -Dlatest=true


  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy-provider:
    runs-on: ubuntu-latest
    needs: provider-verify
    steps:
      - uses: actions/checkout@v3
      - name: Can I deploy provider?
        run: mvn -f ./provider/ pact:can-i-deploy -Dpacticipant='ProductCatalogue' -Dlatest=true

  # Only deploy from master
#  deploy:
#    runs-on: ubuntu-latest
#    needs: can-i-deploy
#    steps:
#      - uses: actions/checkout@v3
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Deploy
#        run: GIT_BRANCH=${GIT_REF:11} make deploy
#        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/test'